### ISSUE TITLE
Chronological order

### ISSUE THREAD

**Issue by odineiramone** [kayaman/resume#1]
Hello @kayaman!

I was reading your resume and note that the items under Education and Independent Coursework are ordered by year on ascending order and the items under Experienc and Awards are ordered by year on descending order.

I don't know if it was intentional but I think it's better open this issue and ask to you 😄 

By the way, nice work experience!

**Comment by kayaman** [comment]
Awesome @odineiramone! Will check it! Thanks for letting me know. 🤘🏻

**Comment by kayaman** [comment]
fixed by #2 
Thank you maninho :)
